"""Added Contact

Revision ID: 95b68f5732a5
Revises: 30e95dc60964
Create Date: 2026-02-17 00:12:22.069192

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '95b68f5732a5'
down_revision = '30e95dc60964'
branch_labels = None
depends_on = None


def upgrade():
    
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    # ### commands auto generated by Alembic - please adjust! ###
    if 'users' not in tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('profile_picture', sa.String(length=255), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('organization_name', sa.String(length=150), nullable=False),
        sa.Column('registration_number', sa.String(length=50), nullable=False),
        sa.Column('business_type', sa.String(length=50), nullable=False),
        sa.Column('points', sa.Integer(), nullable=True),
        sa.Column('impact_tier', sa.String(length=50), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('verification_proof', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('registration_number'),
        sa.UniqueConstraint('username')
    )
    
    if 'audit_logs' not in tables:
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('details', sa.String(length=255), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    if 'contacts' not in tables:    
        op.create_table('contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('contact_user_id', sa.Integer(), nullable=False),
        sa.Column('nickname', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('owner_id', 'contact_user_id', name='_user_contact_uc')
    )
    if 'donations' not in tables:    
        op.create_table('donations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('initial_quantity_kg', sa.Float(), nullable=True),
        sa.Column('quantity_kg', sa.Float(), nullable=True),
        sa.Column('food_type', sa.String(length=50), nullable=True),
        sa.Column('tags', sa.String(length=200), nullable=True),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('donor_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('expiration_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'watchlists' not in tables:    
        op.create_table('watchlists',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('food_type', sa.String(length=50), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if 'claims' not in tables:    
        op.create_table('claims',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('donation_id', sa.Integer(), nullable=False),
            sa.Column('rescuer_id', sa.Integer(), nullable=False),
            sa.Column('quantity_claimed', sa.Float(), nullable=False),
            sa.Column('claimed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.Column('picked_up_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('pickup_code', sa.String(length=10), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
            sa.ForeignKeyConstraint(['rescuer_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('pickup_code')
        )
    if 'messages' not in tables:    
        op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('receiver_id', sa.Integer(), nullable=False),
        sa.Column('donation_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'reports' not in tables:    
        op.create_table('reports',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('reporter_id', sa.Integer(), nullable=False),
            sa.Column('donation_id', sa.Integer(), nullable=False),
            sa.Column('reason', sa.String(length=255), nullable=False),
            sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
            sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if 'tickets' not in tables:    
        op.create_table('tickets',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('reporter_id', sa.Integer(), nullable=False),
            sa.Column('claim_id', sa.Integer(), nullable=True),
            sa.Column('subject', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('priority', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('resolved_at', sa.DateTime(), nullable=True),
            sa.Column('admin_response', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
            sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('reports')
    op.drop_table('messages')
    op.drop_table('claims')
    op.drop_table('watchlists')
    op.drop_table('donations')
    op.drop_table('contacts')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_location', table_name='users', postgresql_using='gist')
    op.drop_table('users')
    # ### end Alembic commands ###
